INSERT INTO domains.network_6_terminalnames (code, description)
VALUES
    (0, 'None'),
    (1, 'Single Terminal'),
    (2, 'DT:Source'),
    (3, 'DT:Load'),
    (4, 'T:Terminal A'),
    (5, 'T:Terminal B'),
    (6, 'T:Terminal C'),
    (7, '2wXFR:Primary'),
    (8, '2wXFR:Secondary'),
    (9, 'V:Terminal A'),
    (10, 'V:Terminal B'),
    (11, 'V:Terminal C'),
    (12, 'INV:DC Input'),
    (13, 'INV:AC Output'),
    (14, 'RT:AC Input'),
    (15, 'RT:DC Output'),
    (16, 'CB:Line Side'),
    (17, 'CB:Bus Side'),
    (18, 'Bypass:Regulator Source'),
    (19, 'Bypass:Regulator Load'),
    (20, 'Bypass:Regulator In Bushing'),
    (21, 'Bypass:Regulator Out Bushing'),
    (22, 'VR:In Bushing'),
    (23, 'VR:Out Bushing'),
    (24, 'HVDS:Bus Side'),
    (25, 'HVDS:Line Side'),
    (26, 'HVIS:Terminal A'),
    (27, 'HVIS:Terminal B'),
    (28, 'RT:Measured Power'),
    (29, 'RT:Communications'),
    (30, 'RT:Aux Power'),
    (31, 'SS:S1'),
    (32, 'SS:S2'),
    (33, 'Power'),
    (34, 'Monitor'),
    (35, 'Communications'),
    (36, '3wXFR:Primary'),
    (37, '3wXFR:Secondary'),
    (38, '3wXFR:Tertiary'),
    (39, 'Line Side'),
    (40, 'Load Side'),
    (41, 'CBD:Line Side'),
    (42, 'CBD:Bus Side'),
    (43, '2wXFRBD:Primary'),
    (44, '2wXFRBD:Secondary'),
    (45, 'GS:Line Side'),
    (46, 'GS:Ground Side'),
    (47, 'TW:Core'),
    (48, 'TW:Bushing');

