INSERT INTO domains.network_6_associationstatus (code, description)
VALUES
    (0, 'None'),
    (1, 'Container'),
    (2, 'Structure'),
    (4, 'Content'),
    (5, 'Content and Container'),
    (6, 'Content and Structure'),
    (8, 'Attachment'),
    (9, 'Attachment and Container'),
    (10, 'Attachment and Structure'),
    (12, 'Attachment and Content'),
    (13, 'Attachment and Content and Container'),
    (14, 'Attachment and Content and Structure'),
    (16, 'Visible Content'),
    (17, 'Visible Content and Container'),
    (18, 'Visible Content and Structure'),
    (24, 'Visible Content and Attachment'),
    (25, 'Visible Content and Attachment and Container'),
    (26, 'Visible Content and Attachment and Structure'),
    (32, 'Connectivity'),
    (33, 'Connectivity and Container'),
    (34, 'Connectivity and Structure'),
    (36, 'Connectivity and Content'),
    (37, 'Connectivity and Content and Container'),
    (38, 'Connectivity and Content and Structure'),
    (40, 'Connectivity and Attachment'),
    (41, 'Connectivity and Attachment and Container'),
    (42, 'Connectivity and Attachment and Structure'),
    (44, 'Connectivity and Attachment and Content'),
    (45, 'Connectivity and Attachment and Content and Container'),
    (46, 'Connectivity and Attachment and Content and Structure'),
    (48, 'Connectivity and Visible Content'),
    (49, 'Connectivity and Visible Content and Container'),
    (50, 'Connectivity and Visible Content and Structure'),
    (56, 'Connectivity and Visible Content and Attachment'),
    (57, 'Connectivity and Visible Content and Attachment and Container'),
    (58, 'Connectivity and Visible Content and Attachment and Structure');

