-- TABLE: electric_transmission_assembly
COMMENT ON TABLE utility_network.electric_transmission_assembly IS 'The Assembly feature class represents complex point features which contain other devices and lines. Like device features, assembly features are compact features but they differ in that assemblies contain other significant devices. Assemblies are useful to show a single symbol on the map yet model the internal features and their connections. Assemblies can contain devices, lines, and junctions. You can view the internal features of an assembly on the map or in the diagram view.';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.global_id IS 'Globally unique Identifier across geodatabases';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.object_id IS 'A unique, not null integer field used to uniquely identify rows in tables in a geodatabase.';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.asset_id IS 'The Asset ID or Facilit ID of the equipment';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.asset_group IS 'The main classification of a utility element.';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.asset_type IS 'A class that refines a utility elements classification within an asset group.';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.association_status IS 'Indicates the type of association a feature or object participates in.';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.construction_status IS 'Used to indicate if the eqiupment is Gang Operable and/or Phase Operable';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.lifecycle_status IS 'The status of the feature in relation to tracing';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.created_user IS 'The portal or dbms user that created the feature or object, per editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.created_date IS 'The date the object or feature was created per editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.last_edited_user IS 'The last user to edit this feature according to editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.last_edited_date IS 'The date this object or feature was last edited according to editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.shape IS 'Geometry of the feature';
COMMENT ON COLUMN utility_network.electric_transmission_assembly.symbol_rotation IS 'The angle the symbol should be rotated by';

-- TABLE: utility_network.electric_transmission_device
COMMENT ON TABLE utility_network.electric_transmission_device IS 'The Device feature class represents features through which your utility resource flows and devices can affect your resource in several ways. Devices can optionally have terminals when there are distinct entry points to the device. Devices can be connected to other devices, junctions, and lines. Devices can be contained within assemblies.';
COMMENT ON COLUMN utility_network.electric_transmission_device.global_id IS 'Globally unique Identifier across geodatabases';
COMMENT ON COLUMN utility_network.electric_transmission_device.object_id IS 'A unique, not null integer field used to uniquely identify rows in tables in a geodatabase.';
COMMENT ON COLUMN utility_network.electric_transmission_device.asset_id IS 'The Asset ID or Facilit ID of the equipment';
COMMENT ON COLUMN utility_network.electric_transmission_device.asset_group IS 'The main classification of a utility element.';
COMMENT ON COLUMN utility_network.electric_transmission_device.asset_type IS 'A class that refines a utility elements classification within an asset group.';
COMMENT ON COLUMN utility_network.electric_transmission_device.association_status IS 'Indicates the type of association a feature or object participates in.';
COMMENT ON COLUMN utility_network.electric_transmission_device.supported_subnetwork_name IS 'a list of subnetwork names that the feature either has an attachment to or contains elements from';
COMMENT ON COLUMN utility_network.electric_transmission_device.construction_status IS 'Used to indicate if the eqiupment is Gang Operable and/or Phase Operable';
COMMENT ON COLUMN utility_network.electric_transmission_device.lifecycle_status IS 'The status of the feature in relation to tracing';
COMMENT ON COLUMN utility_network.electric_transmission_device.created_user IS 'The portal or dbms user that created the feature or object, per editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_device.created_date IS 'The date the object or feature was created per editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_device.last_edited_user IS 'The last user to edit this feature according to editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_device.last_edited_date IS 'The date this object or feature was last edited according to editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_device.shape IS 'Geometry of the feature';
COMMENT ON COLUMN utility_network.electric_transmission_device.symbol_rotation IS 'The angle the symbol should be rotated by';
COMMENT ON COLUMN utility_network.electric_transmission_device.is_connected IS 'An indicator that an object is connected to a subnetwork in the utility network and can be used to identify isolated objects';
COMMENT ON COLUMN utility_network.electric_transmission_device.is_subnetwork_controller IS 'An indicator that an object is a subnetwork controller in the utility network';
COMMENT ON COLUMN utility_network.electric_transmission_device.subnetwork_controller_name IS 'The unique name of the subnetwork controller in the tier';
COMMENT ON COLUMN utility_network.electric_transmission_device.tier_name IS 'The name of the tier to which the subnetwork belongs';
COMMENT ON COLUMN utility_network.electric_transmission_device.tier_rank IS 'The rank number assigned to the tier to which the subnetwork belongs';
COMMENT ON COLUMN utility_network.electric_transmission_device.terminal_path IS 'terminal configuration used which defines the terminals and the paths between them';
COMMENT ON COLUMN utility_network.electric_transmission_device.subnetwork_name IS 'a list of subnetwork names that the feature participates in';
COMMENT ON COLUMN utility_network.electric_transmission_device.supporting_subnetwork_name IS 'a list of subnetwork names that the feature is contained in';
COMMENT ON COLUMN utility_network.electric_transmission_device.normal_status IS 'The normal state for a swtichable device';
COMMENT ON COLUMN utility_network.electric_transmission_device.phases_normal IS 'The phases resulting from Normal switching states';
COMMENT ON COLUMN utility_network.electric_transmission_device.primary_nominal_voltage_ll IS 'The named line to line voltage measured in Volts';
COMMENT ON COLUMN utility_network.electric_transmission_device.secondary_voltage_line_to_line IS 'The named Secondary line to line voltage measured in Volts';
COMMENT ON COLUMN utility_network.electric_transmission_device.secondary_voltage_line_to_ground IS 'The named Secondary line to neutral or ground measured in Voltage';
COMMENT ON COLUMN utility_network.electric_transmission_device.secondary_winding_grounding IS 'Attribute to define the AC system grounding type of Delta or Wye on the Secondary Winding';
COMMENT ON COLUMN utility_network.electric_transmission_device.tertiary_voltage_line_to_line IS 'The named Tertiary line to line voltage measured in Volts';
COMMENT ON COLUMN utility_network.electric_transmission_device.tertiary_voltage_line_to_ground IS 'The named Tertiary line to neutral or ground measured in Voltage';
COMMENT ON COLUMN utility_network.electric_transmission_device.tertiary_winding_grounding IS 'Attribute to define the AC system grounding type of Delta or Wye on the Tertiary winding';
COMMENT ON COLUMN utility_network.electric_transmission_device.maximum_voltage IS 'The maximum voltage the equipment can sustain';
COMMENT ON COLUMN utility_network.electric_transmission_device.maximum_operating_voltage IS 'The maximum voltage the equipment can be reliable operated at';
COMMENT ON COLUMN utility_network.electric_transmission_device.peak_load IS 'The maximum sustained load experienced by a power consumer';
COMMENT ON COLUMN utility_network.electric_transmission_device.rated_power IS 'The Rated Power for the equipment';
COMMENT ON COLUMN utility_network.electric_transmission_device.primary_to_secondary_winding_vector_group IS 'The IEC category used to describe the winding configurations and phase angle differences between the Primary and Secondary windings of a three phase transformer';
COMMENT ON COLUMN utility_network.electric_transmission_device.primary_to_tertiary_winding_vector_group IS 'The IEC category used to describe the winding configurations and phase angle differences between the Primary and Tertiary windings of a three phase transformer';
COMMENT ON COLUMN utility_network.electric_transmission_device.section_id IS 'The Electrical Section this equipment is associated with';
COMMENT ON COLUMN utility_network.electric_transmission_device.section_terminal IS 'The UN terminal used for this section';
COMMENT ON COLUMN utility_network.electric_transmission_device.is_riser IS 'Indicates that this equipment also acts as a riser or dip';
COMMENT ON COLUMN utility_network.electric_transmission_device.section_start_or_end_indicator IS 'Indicates that this equipment is the start of a section';

-- TABLE: electric_transmission_junction
COMMENT ON TABLE utility_network.electric_transmission_junction IS 'The Junction class represents locations where lines connect to lines or lines connect to devices. A key use for junction features is to allow devices or lines to connect to another line at an intermediate vertex. You can think of a junction as glue point at key places to connect all the features of a utility network. Junctions can be contained within assemblies.';
COMMENT ON COLUMN utility_network.electric_transmission_junction.global_id IS 'Globally unique Identifier across geodatabases';
COMMENT ON COLUMN utility_network.electric_transmission_junction.object_id IS 'A unique, not null integer field used to uniquely identify rows in tables in a geodatabase.';
COMMENT ON COLUMN utility_network.electric_transmission_junction.asset_id IS 'The Asset ID or Facilit ID of the equipment';
COMMENT ON COLUMN utility_network.electric_transmission_junction.asset_group IS 'The main classification of a utility element.';
COMMENT ON COLUMN utility_network.electric_transmission_junction.asset_type IS 'A class that refines a utility elements classification within an asset group.';
COMMENT ON COLUMN utility_network.electric_transmission_junction.association_status IS 'Indicates the type of association a feature or object participates in.';
COMMENT ON COLUMN utility_network.electric_transmission_junction.subnetwork_name IS 'a list of subnetwork names that the feature participates in';
COMMENT ON COLUMN utility_network.electric_transmission_junction.supported_subnetwork_name IS 'a list of subnetwork names that the feature either has an attachment to or contains elements from';
COMMENT ON COLUMN utility_network.electric_transmission_junction.supporting_subnetwork_name IS 'a list of subnetwork names that the feature is contained in';
COMMENT ON COLUMN utility_network.electric_transmission_junction.construction_status IS 'Used to indicate if the eqiupment is Gang Operable and/or Phase Operable';
COMMENT ON COLUMN utility_network.electric_transmission_junction.lifecycle_status IS 'The status of the feature in relation to tracing';
COMMENT ON COLUMN utility_network.electric_transmission_junction.created_user IS 'The portal or dbms user that created the feature or object, per editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_junction.created_date IS 'The date the object or feature was created per editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_junction.last_edited_user IS 'The last user to edit this feature according to editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_junction.last_edited_date IS 'The date this object or feature was last edited according to editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_junction.shape IS 'Geometry of the feature';
COMMENT ON COLUMN utility_network.electric_transmission_junction.symbol_rotation IS 'The angle the symbol should be rotated by';
COMMENT ON COLUMN utility_network.electric_transmission_junction.is_connected IS 'An indicator that an object is connected to a subnetwork in the utility network and can be used to identify isolated objects';
COMMENT ON COLUMN utility_network.electric_transmission_junction.supporting_subnetwork_name IS 'a list of subnetwork names that the feature is contained in';
COMMENT ON COLUMN utility_network.electric_transmission_junction.phases_normal IS 'The phases resulting from Normal switching states';
COMMENT ON COLUMN utility_network.electric_transmission_junction.is_riser IS 'Indicates that this equipment also acts as a riser or dip';
COMMENT ON COLUMN utility_network.electric_transmission_junction.section_id IS 'The Electrical Section this equipment is associated with';

-- TABLE: electric_transmission_line
COMMENT ON TABLE utility_network.electric_transmission_line IS 'The Line feature class represents linear features. These are the lines which deliver your utility resource. Lines can be connected to other lines, junctions, and devices. Lines can be contained within assemblies.';
COMMENT ON COLUMN utility_network.electric_transmission_line.global_id IS 'Globally unique Identifier across geodatabases';
COMMENT ON COLUMN utility_network.electric_transmission_line.object_id IS 'A unique, not null integer field used to uniquely identify rows in tables in a geodatabase.';
COMMENT ON COLUMN utility_network.electric_transmission_line.asset_id IS 'The Asset ID or Facilit ID of the equipment';
COMMENT ON COLUMN utility_network.electric_transmission_line.asset_group IS 'The main classification of a utility element.';
COMMENT ON COLUMN utility_network.electric_transmission_line.asset_type IS 'A class that refines a utility elements classification within an asset group.';
COMMENT ON COLUMN utility_network.electric_transmission_line.association_status IS 'Indicates the type of association a feature or object participates in.';
COMMENT ON COLUMN utility_network.electric_transmission_line.subnetwork_name IS 'a list of subnetwork names that the feature participates in';
COMMENT ON COLUMN utility_network.electric_transmission_line.supported_subnetwork_name IS 'a list of subnetwork names that the feature either has an attachment to or contains elements from';
COMMENT ON COLUMN utility_network.electric_transmission_line.supporting_subnetwork_name IS 'a list of subnetwork names that the feature is contained in';
COMMENT ON COLUMN utility_network.electric_transmission_line.construction_status IS 'Used to indicate if the eqiupment is Gang Operable and/or Phase Operable';
COMMENT ON COLUMN utility_network.electric_transmission_line.lifecycle_status IS 'The status of the feature in relation to tracing';
COMMENT ON COLUMN utility_network.electric_transmission_line.created_user IS 'The portal or dbms user that created the feature or object, per editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_line.created_date IS 'The date the object or feature was created per editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_line.last_edited_user IS 'The last user to edit this feature according to editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_line.last_edited_date IS 'The date this object or feature was last edited according to editor tracking';
COMMENT ON COLUMN utility_network.electric_transmission_line.shape IS 'Geometry of the feature';
COMMENT ON COLUMN utility_network.electric_transmission_line.phases_normal IS 'The phases resulting from Normal switching states';
COMMENT ON COLUMN utility_network.electric_transmission_line.maximum_voltage IS 'The maximum voltage the equipment can sustain';
COMMENT ON COLUMN utility_network.electric_transmission_line.maximum_operating_voltage IS 'The maximum voltage the equipment can be reliable operated at';
COMMENT ON COLUMN utility_network.electric_transmission_line.nominal_voltage_ll IS 'The named line to line voltage measured in Volts';
COMMENT ON COLUMN utility_network.electric_transmission_line.grounding IS 'Attribute to define the AC system grounding type of Delta or Wye';
COMMENT ON COLUMN utility_network.electric_transmission_line.measured_length IS 'The actual length of the cable, duct, conduit, trench';
COMMENT ON COLUMN utility_network.electric_transmission_line.ohm_per_length IS 'The electrical resistance measured in ohms of the cable';
COMMENT ON COLUMN utility_network.electric_transmission_line.section_id IS 'The Electrical Section this equipment is associated with';

-- TABLE: service_territory
COMMENT ON TABLE utility_network.service_territory IS 'The networks service territory that represents the operational area of the utility.';
COMMENT ON COLUMN utility_network.service_territory.global_id IS 'Globally unique Identifier across geodatabases';
COMMENT ON COLUMN utility_network.service_territory.object_id IS 'A unique, not null integer field used to uniquely identify rows in tables in a geodatabase.';
COMMENT ON COLUMN utility_network.service_territory.created_user IS 'The portal or dbms user that created the feature or object, per editor tracking';
COMMENT ON COLUMN utility_network.service_territory.created_date IS 'The date the object or feature was created per editor tracking';
COMMENT ON COLUMN utility_network.service_territory.last_edited_user IS 'The last user to edit this feature according to editor tracking';
COMMENT ON COLUMN utility_network.service_territory.last_edited_date IS 'The date this object or feature was last edited according to editor tracking';
COMMENT ON COLUMN utility_network.service_territory.shape IS 'Geometry of the feature';
COMMENT ON COLUMN utility_network.service_territory.company_name IS 'The company name of this service area polygon';
COMMENT ON COLUMN utility_network.service_territory.district_name IS 'The name of the district ';

-- TABLE: structure_boundary
COMMENT ON TABLE utility_network.structure_boundary IS 'The Structure Boundary feature class represents features whose outline should be display on a map view or container view. Structure boundaries can contain structure edges, structure junctions, devices, lines, assemblies, and junctions.';
COMMENT ON COLUMN utility_network.structure_boundary.global_id IS 'Globally unique Identifier across geodatabases';
COMMENT ON COLUMN utility_network.structure_boundary.object_id IS 'A unique, not null integer field used to uniquely identify rows in tables in a geodatabase.';
COMMENT ON COLUMN utility_network.structure_boundary.asset_id IS 'The Asset ID or Facilit ID of the equipment';
COMMENT ON COLUMN utility_network.structure_boundary.asset_group IS 'The main classification of a utility element.';
COMMENT ON COLUMN utility_network.structure_boundary.asset_type IS 'A class that refines a utility elements classification within an asset group.';
COMMENT ON COLUMN utility_network.structure_boundary.association_status IS 'Indicates the type of association a feature or object participates in.';
COMMENT ON COLUMN utility_network.structure_boundary.supported_subnetwork_name IS 'a list of subnetwork names that the feature either has an attachment to or contains elements from';
COMMENT ON COLUMN utility_network.structure_boundary.construction_status IS 'Used to indicate if the eqiupment is Gang Operable and/or Phase Operable';
COMMENT ON COLUMN utility_network.structure_boundary.lifecycle_status IS 'The status of the feature in relation to tracing';
COMMENT ON COLUMN utility_network.structure_boundary.created_user IS 'The portal or dbms user that created the feature or object, per editor tracking';
COMMENT ON COLUMN utility_network.structure_boundary.created_date IS 'The date the object or feature was created per editor tracking';
COMMENT ON COLUMN utility_network.structure_boundary.last_edited_user IS 'The last user to edit this feature according to editor tracking';
COMMENT ON COLUMN utility_network.structure_boundary.last_edited_date IS 'The date this object or feature was last edited according to editor tracking';
COMMENT ON COLUMN utility_network.structure_boundary.shape IS 'Geometry of the feature';
COMMENT ON COLUMN utility_network.structure_boundary.name IS 'The name of the facility, like a station name';
COMMENT ON COLUMN utility_network.structure_boundary.maximum_kw IS 'The electrical units of measure used with this equipment, watts, volt amps,volt amps ractive ';
COMMENT ON COLUMN utility_network.structure_boundary.contained_count IS 'The number of features/objects contained in this feature';

-- TABLE: structure_junction
COMMENT ON TABLE utility_network.structure_junction IS 'The Structure Junction feature class represents features which are tracked in a utilitys asset inventory system. A structure junction can be either a structural feature that a device is attached to or a container of devices.';
COMMENT ON COLUMN utility_network.structure_junction.global_id IS 'Globally unique Identifier across geodatabases';
COMMENT ON COLUMN utility_network.structure_junction.object_id IS 'A unique, not null integer field used to uniquely identify rows in tables in a geodatabase.';
COMMENT ON COLUMN utility_network.structure_junction.asset_id IS 'The Asset ID or Facilit ID of the equipment';
COMMENT ON COLUMN utility_network.structure_junction.asset_group IS 'The main classification of a utility element.';
COMMENT ON COLUMN utility_network.structure_junction.asset_type IS 'A class that refines a utility elements classification within an asset group.';
COMMENT ON COLUMN utility_network.structure_junction.association_status IS 'Indicates the type of association a feature or object participates in.';
COMMENT ON COLUMN utility_network.structure_junction.supported_subnetwork_name IS 'a list of subnetwork names that the feature either has an attachment to or contains elements from';
COMMENT ON COLUMN utility_network.structure_junction.construction_status IS 'Used to indicate if the eqiupment is Gang Operable and/or Phase Operable';
COMMENT ON COLUMN utility_network.structure_junction.lifecycle_status IS 'The status of the feature in relation to tracing';
COMMENT ON COLUMN utility_network.structure_junction.created_user IS 'The portal or dbms user that created the feature or object, per editor tracking';
COMMENT ON COLUMN utility_network.structure_junction.created_date IS 'The date the object or feature was created per editor tracking';
COMMENT ON COLUMN utility_network.structure_junction.last_edited_user IS 'The last user to edit this feature according to editor tracking';
COMMENT ON COLUMN utility_network.structure_junction.last_edited_date IS 'The date this object or feature was last edited according to editor tracking';
COMMENT ON COLUMN utility_network.structure_junction.shape IS 'Geometry of the feature';
COMMENT ON COLUMN utility_network.structure_junction.symbol_rotation IS 'The angle the symbol should be rotated by';
COMMENT ON COLUMN utility_network.structure_junction.height IS 'The heighth of this structure';
COMMENT ON COLUMN utility_network.structure_junction.treatment IS 'The method or material used to treat the structure';
COMMENT ON COLUMN utility_network.structure_junction.equipment_type_or_class IS 'An extra attribute to futher define equipment type without adding an additional asset type';
COMMENT ON COLUMN utility_network.structure_junction.type_marker IS 'Describes the type of marker indicator, such as lighted';
COMMENT ON COLUMN utility_network.structure_junction.structure_grounded IS 'Indicator that this structure is properly grounded';

-- TABLE: structure_line
COMMENT ON TABLE utility_network.structure_line IS 'The Structure Line contain lines which carry a resource. Structure lines participating as containers can contain other structure lines.';
COMMENT ON COLUMN utility_network.structure_line.global_id IS 'Globally unique Identifier across geodatabases';
COMMENT ON COLUMN utility_network.structure_line.object_id IS 'A unique, not null integer field used to uniquely identify rows in tables in a geodatabase.';
COMMENT ON COLUMN utility_network.structure_line.asset_id IS 'The Asset ID or Facilit ID of the equipment';
COMMENT ON COLUMN utility_network.structure_line.asset_group IS 'The main classification of a utility element.';
COMMENT ON COLUMN utility_network.structure_line.asset_type IS 'A class that refines a utility elements classification within an asset group.';
COMMENT ON COLUMN utility_network.structure_line.association_status IS 'Indicates the type of association a feature or object participates in.';
COMMENT ON COLUMN utility_network.structure_line.supported_subnetwork_name IS 'a list of subnetwork names that the feature either has an attachment to or contains elements from';
COMMENT ON COLUMN utility_network.structure_line.construction_status IS 'Used to indicate if the eqiupment is Gang Operable and/or Phase Operable';
COMMENT ON COLUMN utility_network.structure_line.lifecycle_status IS 'The status of the feature in relation to tracing';
COMMENT ON COLUMN utility_network.structure_line.created_user IS 'The portal or dbms user that created the feature or object, per editor tracking';
COMMENT ON COLUMN utility_network.structure_line.created_date IS 'The date the object or feature was created per editor tracking';
COMMENT ON COLUMN utility_network.structure_line.last_edited_user IS 'The last user to edit this feature according to editor tracking';
COMMENT ON COLUMN utility_network.structure_line.last_edited_date IS 'The date this object or feature was last edited according to editor tracking';
COMMENT ON COLUMN utility_network.structure_line.shape IS 'Geometry of the feature';
